# A list of object files to be combined into the final scull.o module object.
scull-objs := main.o pipe.o access.o

# Tell kbuild to build the 'scull.o' module if CONFIG_SCULL is enabled.
obj-$(CONFIG_SCULL) += scull.o
